version: "3.7"
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=bdi89uwe31gdi121uy@7!#!@
      - TZ=Asia/Taipei`
    ports:
      - "1433:1433"
    volumes:
      - "./bak:/var/bak"